config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # SIDEKIQ
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # WELCOME/INDEX
  root 'welcome#index'

  # OROSHI
  namespace :oroshi do
    root to: 'dashboard#index'

    namespace :dashboard do
      %w[home suppliers_organizations supply_types
         shipping buyers materials products stats company].each do |tab|
        get tab
      end
      get 'subregions'
      post 'company_settings'
    end

    resources :supply_reception_times, except: %i[destroy show]

    resources :supplier_organizations, except: %i[show destroy] do
      get 'load', on: :collection
      get 'load', on: :member
      resources :suppliers, only: %i[new index]
    end

    resources :suppliers, except: %i[destroy show]

    resources :supply_types, except: %i[destroy show] do
      get 'load', on: :collection
      get 'load', on: :member
      resources :supply_type_variations, only: %i[new index]
    end

    resources :supply_type_variations, except: %i[destroy show]

    resources :supply_dates, param: :date, except: :destroy do
      post 'entry/:supplier_organization_id/:supply_reception_time_id',
           on: :member, to: 'supply_dates#entry', as: :entry
      get 'checklist/:subregion_ids/:supply_reception_time_ids',
          on: :member, to: 'supply_dates#checklist', as: :checklist
      get 'supply_invoice_actions', on: :collection
      get 'supply_price_actions', on: :collection
      post 'set_supply_prices', on: :collection
    end

    resources :supplies, only: %i[index show update] # new and create are handled by supply_dates
    get 'supplies/entry', to: 'supplies#new', as: :supply_entry

    get 'invoices/preview', as: :invoice_preview, to: 'invoices#preview'
    resources :invoices do
      get :send_mail_now, on: :member
      get :mail_notification_preview, on: :member
    end

    resources :shipping_organizations, except: :destroy do
      get 'load', on: :collection
      get 'load', on: :member
      resources :shipping_methods, only: %i[new index]
    end

    resources :shipping_methods, except: %i[destroy show]

    resources :buyers, except: %i[destroy show] do
      get 'orders/:date', on: :member, to: 'buyers#bundlable_orders', as: :bundlable_orders
    end

    resources :shipping_receptacles, except: %i[destroy show] do
      get 'image', on: :member
      get 'estimate_per_box_quantity/:product_variation_id',
          to: 'shipping_receptacles#estimate_per_box_quantity',
          on: :member
    end

    resources :packagings, except: %i[destroy show] do
      get 'image', on: :member
      get 'images', on: :collection
    end

    resources :material_categories, except: %i[destroy show] do
      resources :materials, only: %i[index]
    end

    resources :materials, except: %i[index destroy show] do
      get 'image', on: :member
      get 'images', on: :collection
    end

    resources :products, except: %i[destroy show] do
      get 'load', on: :collection
      get 'load', on: :member
      resources :product_variations, only: %i[new index]
      get 'material_cost/:shipping_receptacle_id/:item_quantity/:receptacle_quantity/:freight_quantity',
          on: :member,
          to: 'products#material_cost'
      patch 'update_positions', on: :collection
    end

    resources :product_variations, except: %i[destroy show] do
      get 'load', on: :collection
      get 'load', on: :member
      get 'image', on: :member
      get 'cost', on: :member
    end

    resources :production_zones, except: %i[destroy show]

    get 'orders/calendar', to: 'orders#calendar', as: :orders_calendar
    get 'orders/calendar/orders', to: 'orders#calendar_orders', as: :calendar_orders
    get 'orders(/:date)', to: 'orders#index', as: :orders
    get 'orders(/:date)/new', to: 'orders#new', as: :new_order
    post 'orders/from_template/:template_id', to: 'orders#new_order_from_template', as: :new_order_from_template
    delete 'orders/templates/:template_id', to: 'orders#destroy_template', as: :delete_template
    patch 'orders/:id/quantity_update', to: 'orders#quantity_update', as: :quantity_update_order
    patch 'orders/:id/price_update', to: 'orders#price_update', as: :price_update_order

    scope 'orders/:date', as: :orders do
      %w[orders templates production shipping sales revenue].each do |route|
        get "/#{route}", to: "orders##{route}", as: route.to_sym
      end
      get '/buyer_sales/:buyer_id', to: 'orders#buyer_sales', as: :buyer_sales
      get '/supply_volumes', to: 'orders#supply_volumes', as: :order_supply_volumes
      get '/product_inventories', to: 'orders#product_inventories', as: :order_product_inventories
      get '/production_view/:production_view', to: 'orders#production_view', as: :order_production_view
    end

    resources :orders, except: %i[index new show] do
      get 'show', to: 'orders#show', as: :show
    end

    resources :product_inventories, except: %i[destroy] do
      resources :production_requests, only: %i[index]
    end

    resources :production_requests, except: %i[index] do
      get 'convert/:date(/:product_id)', on: :collection, to: 'production_requests#convert', as: :convert
    end
  end

  # ASYNC AND JS
  get '/load_rakuten_orders/:date' => 'welcome#load_rakuten_orders', as: 'load_rakuten_orders'
  get '/load_funabiki_order/:date' => 'welcome#load_funabiki_orders', as: 'load_funabiki_orders'
  get '/load_yahoo_orders/:date' => 'welcome#load_yahoo_orders', as: 'load_yahoo_orders'
  get '/load_infomart_orders/:date' => 'welcome#load_infomart_orders', as: 'load_infomart_orders'
  get '/reciept/', as: 'reciept', to: 'welcome#reciept'
  get '/insert_receipt_data' => 'welcome#insert_receipt_data', as: 'insert_receipt_data'

  # WELCOME WIDGETS
  get :daily_expiration_cards, controller: :welcome
  get :rakuten_orders_fp, controller: :welcome
  get :receipt_partial, controller: :welcome
  get :front_infomart_orders, controller: :welcome
  get :infomart_shinki_modal, controller: :welcome
  get :funabiki_orders_partial, controller: :welcome
  get :funabiki_orders_modal, controller: :welcome
  get :yahoo_orders_partial, controller: :welcome
  get :new_yahoo_orders_modal, controller: :welcome
  get :rakuten_shinki_modal, controller: :welcome
  get :charts_partial, controller: :welcome
  get :printables, controller: :welcome

  # FORCAST
  get 'forcasts(/:date)' => 'forcasts#index', as: 'forcasts'
  get 'fetch_week_forcast/:date' => 'forcasts#fetch_week_forcast', as: 'fetch_week_forcast'
  get :week_forcast, controller: :forcasts
  get 'fetch_forcast_calendar_counts(/:date)', as: :fetch_forcast_calendar_counts,
                                               to: 'forcasts#fetch_forcast_calendar_counts', defaults: { format: 'js' }
  get 'fetch_forcast_calendar_forcasts(/:date)', as: :fetch_cforcast_alendar_forcasts,
                                                 to: 'forcasts#fetch_forcast_calendar_forcasts', defaults: { format: 'js' }
  get 'forcast_calendar_event_tippy/:date', as: :forcast_calendar_event_tippy,
                                            to: 'forcasts#forcast_calendar_event_tippy'
  get 'count_calendar_event_tippy/:date', as: :count_calendar_event_tippy, to: 'forcasts#count_calendar_event_tippy'

  # ANALYSIS
  get 'analysis' => 'analysis#index', as: 'analysis'
  get '/fetch_analysis' => 'analysis#fetch_analysis', as: 'fetch_analysis'
  get :total_profit_estimate_analysis_chart_partial, controller: :analysis
  get :market_profit_analysis_chart_partial, controller: :analysis
  get :oyster_sales_kilo_price_analysis_chart_partial, controller: :analysis
  get :oyster_market_kilo_price_analysis_chart_partial, controller: :analysis
  get :oyster_volume_analysis_chart_partial, controller: :analysis
  get :online_shop_order_count_chart_partial, controller: :analysis
  get :online_shop_order_sales_chart_partial, controller: :analysis
  get :furusato_order_count_chart_partial, controller: :analysis

  # ANALYSIS CHARTS
  get '/fetch_chart/:chart_params' => 'analysis#fetch_chart', as: 'fetch_chart'
  get '/market_profit_analysis_chart' => 'analysis#market_profit_analysis_chart', as: 'market_profit_analysis_chart'
  get '/total_profit_estimate_analysis_chart' => 'analysis#total_profit_estimate_analysis_chart',
      as: 'total_profit_estimate_analysis_chart'
  get '/oyster_sales_kilo_price_analysis_chart' => 'analysis#oyster_sales_kilo_price_analysis_chart',
      as: 'oyster_sales_kilo_price_analysis_chart'
  get '/oyster_market_kilo_price_analysis_chart' => 'analysis#oyster_market_kilo_price_analysis_chart',
      as: 'oyster_market_kilo_price_analysis_chart'
  get '/oyster_volume_analysis_chart' => 'analysis#oyster_volume_analysis_chart', as: 'oyster_volume_analysis_chart'
  get '/online_shop_order_count_chart' => 'analysis#online_shop_order_count_chart', as: 'online_shop_order_count_chart'
  get '/online_shop_order_sales_chart' => 'analysis#online_shop_order_sales_chart', as: 'online_shop_order_sales_chart'
  get '/furusato_order_count_chart' => 'analysis#furusato_order_count_chart', as: 'furusato_order_count_chart'

  # MESSAGES
  get '/messages/:id/download(/:file_name)', to: 'messages#download', as: 'download_message'
  get '/messages' => 'messages#index', as: 'messages'
  get '/messages/:id/:turbo_action' => 'messages#show', as: 'message'
  delete '/messages/:id' => 'messages#destroy', as: 'destroy_message'
  get '/message/:id', to: 'messages#content', as: 'message_content'
  get '/message/refresh/:id', to: 'messages#refresh', as: 'refresh_message'

  # FROZEN OYSTERS
  resources :frozen_oysters
  get '/insert_frozen_data' => 'frozen_oysters#insert_frozen_data', as: 'insert_frozen_data'

  # EXPIRATION CARDS
  resources :expiration_cards do
    get 'download/:file_name', on: :member, constraints: { format: 'pdf' },

app/models/material.rb
class Material < ApplicationRecord
  has_many :product_and_material_joins
  has_many :products, through: :product_and_material_joins
  serialize :history

  validates :namae,
            presence: true,
            length: { minimum: 1 }
  validates :zairyou,
            presence: true,
            length: { minimum: 1 }
  validates :cost,
            presence: true,
            length: { minimum: 1 }
end

app/models/oroshi.rb
# Module: Oroshi (Oroshi, or 卸し, means "wholesale" in Japanese)
# This module is used to store all the classes and modules for the Oroshi application
# To get a list of constants for use with erd (domain name mapping graphics), use:
# Oroshi.constants.map{|c| "Oroshi::#{c.to_s}" unless c.to_s.include?('Controller') || c.to_s.include?('Helper') || c.to_s.include?('Worker') }.compact.join(', ')
# e.g. (in the terminal):
# rails erd only="Oroshi::SupplyType, Oroshi::Invoice, Oroshi::SupplyReceptionTime, Oroshi::Product, Oroshi::Material, Oroshi::Supplier, Oroshi::Address, Oroshi::Buyer, Oroshi::Order, Oroshi::OrderTemplate, Oroshi::Packaging, Oroshi::ProductInventory, Oroshi::ProductVariation, Oroshi::ProductionRequest, Oroshi::ProductionZone, Oroshi::ShippingMethod, Oroshi::ShippingOrganization, Oroshi::ShippingReceptacle, Oroshi::Supply, Oroshi::SupplierOrganization, Oroshi::SupplyTypeVariation, Oroshi::SupplyDate, Oroshi::Invoice::SupplierOrganization, Oroshi::Invoice::SupplyDate, Oroshi::SupplyDate::SupplyTypeVariation, Oroshi::SupplyDate::SupplyType"
# optional additions: "ActiveStorage::VariantRecord, ActiveStorage::Blob, ActiveStorage::Attachment, Message"

module Oroshi
  def self.table_name_prefix
    'oroshi_'
  end
end

app/models/oroshi/activatable.rb
module Oroshi
  module Activatable
    extend ActiveSupport::Concern

    included do
      validates :active, inclusion: { in: [true, false] }
      scope :active, -> { where(active: true) }
      scope :inactive, -> { where(active: false) }
    end
  end
end

app/models/oroshi/address.rb
module Oroshi
  class Address < ApplicationRecord
    # Associations
    belongs_to :addressable, polymorphic: true

    # Validations
    # empty addresses are allowed

    def country
      Carmen::Country.coded(country_id.to_s.rjust(3, '0'))
    end

    def subregion
      country.subregions.coded(subregion_id.to_s)
    end

    def invoice_line
      # 〒678-0232 兵庫県赤穂市中広1576―11
      "#{subregion}#{city}#{address1} #{address2}"
    end
  end
end

app/models/oroshi/buyer.rb
module Oroshi
  class Buyer < ApplicationRecord
    # Callbacks
    include Oroshi::Activatable

    # Associations
    has_many :addresses, class_name: 'Oroshi::Address', as: :addressable
    accepts_nested_attributes_for :addresses

    has_and_belongs_to_many :shipping_methods,
                            class_name: 'Oroshi::ShippingMethod',
                            join_table: 'oroshi_buyers_shipping_methods'
    has_many :shipping_organizations, through: :shipping_methods

    has_many :orders, class_name: 'Oroshi::Order'

    enum entity_type: { wholesale_market: 0, retailer: 1, company: 2, individual: 3, other: 4 }

    # Validations
    validates :name, :handle, :handling_cost, :daily_cost, :entity_type,
              :optional_cost, :commission_percentage, presence: true
    validates :name, :handle, :representative_phone, :fax,
              :associated_system_id, uniqueness: true, allow_blank: true
    validates :color, format: { with: /\A#(?:[0-9a-fA-F]{3}){1,2}\z/, message: "有効な16進数カラーでなければならない" }

    # Scopes
    scope :order_by_associated_system_id, -> { order(:associated_system_id) }

    def orders_with_date(date)
      orders.where(shipping_date: date)
    end
  end
end

app/models/oroshi/invoice.rb
module Oroshi
  class Invoice < ApplicationRecord
    # Callbacks
    before_destroy :ensure_not_sent

    # Associations
    has_many :invoice_supply_dates, class_name: 'Oroshi::Invoice::SupplyDate', dependent: :destroy
    has_many :supply_dates, through: :invoice_supply_dates
    has_many :supplies, through: :supply_dates
    has_many :invoice_supplier_organizations, class_name: 'Oroshi::Invoice::SupplierOrganization', dependent: :destroy
    has_many :supplier_organizations, through: :invoice_supplier_organizations

    # Validations
    validates :start_date, :end_date, :invoice_layout, presence: true
    validates :send_email, inclusion: { in: [true, false] }
    validates :send_at, presence: true, if: :send_email?
    validate :at_least_one_supplier_organization

    # Enums
    enum invoice_layout: { standard: 1, simple: 2 }

    # Broadcasts
    broadcasts :invoice, inserts_by: :replace

    # Scopes
    scope :unsent, -> { where(send_email: true, sent_at: nil).where('send_at <= ?', Time.zone.now) }

    private

    def at_least_one_supplier_organization
      errors.add(:supplier_organizations, "少なくとも1つ必要です") if supplier_organizations.empty?
    end

    def ensure_not_sent
      return unless sent_at.present?

      errors.add(:base, "送信済みの仕切り書を削除できません。")
      throw(:abort)
    end
  end
end

app/models/oroshi/invoice/supplier_organization.rb
class Oroshi::Invoice::SupplierOrganization < ApplicationRecord
  # Associations
  belongs_to :invoice, class_name: 'Oroshi::Invoice'
  belongs_to :supplier_organization, class_name: 'Oroshi::SupplierOrganization'

  # Attachments
  has_many_attached :invoices

  # Callbacks
  after_destroy :purge_invoices

  private

  def purge_invoices
    invoices.purge
  end
end

app/models/oroshi/invoice/supply_date.rb
class Oroshi::Invoice::SupplyDate < ApplicationRecord
  # Callbacks
  after_create :lock_supplies
  before_destroy :unlock_supplies

  # Associations
  belongs_to :invoice, class_name: 'Oroshi::Invoice'
  belongs_to :supply_date, class_name: 'Oroshi::SupplyDate'

  def supplies_with_invoice_supplier_organizations
    supply_date.supplies.joins(:supplier)
               .where(oroshi_suppliers: { supplier_organization_id: invoice.supplier_organization_ids })
  end

  private

  def lock_supplies
    supplies_with_invoice_supplier_organizations.update_all(locked: true)
  end

  def unlock_supplies
    supplies_with_invoice_supplier_organizations.update_all(locked: false)
  end
end

app/models/oroshi/material.rb
module Oroshi
  class Material < ApplicationRecord
    # Callbacks
    include Oroshi::Activatable

    # Attachments
    has_one_attached :image

    # Associations
    has_and_belongs_to_many :products,
                            class_name: 'Oroshi::Product',
                            join_table: 'oroshi_product_materials'
    belongs_to :material_category

    # Validations
    validates :name, :per, presence: true
    validates :cost, presence: true, numericality: true

    # Enum
    enum per: { item: 0, shipping_receptacle: 1, freight: 2, supply_type_unit: 3 }
  end
end

app/models/oroshi/material_category.rb
module Oroshi
  class MaterialCategory < ApplicationRecord
    # Callbacks
    include Oroshi::Activatable

    # Associations
    has_many :materials, class_name: 'Oroshi::Material', dependent: :destroy

    # Validations
    validates :name, presence: true
  end
end

app/models/oroshi/packaging.rb
module Oroshi
  class Packaging < ApplicationRecord
    # Callbacks
    include Oroshi::Activatable

    # Attachments
    has_one_attached :image

    # Associations
    has_and_belongs_to_many :product_variations,
                            class_name: 'Oroshi::ProductVariation',
                            join_table: 'oroshi_product_variation_packagings'
    belongs_to :product, class_name: 'Oroshi::Product', optional: true

    # Validations
    validates :name, presence: true
    validates :cost, presence: true, numericality: true

    # Scopes
    # product_id nil means that the packaging is a global packaging
    scope :global_packaging, -> { where(product_id: nil) }
  end
end

app/views/oroshi/materials/_form.html.erb
<% if @material.errors.any? %>
  <div id="error_explanation" class="m-auto mb-2">
    <h2><%= @material.errors.count %>のエラーがこの供給受付時間の保存を禁止しました</h2>

    <ul>
    <% @material.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="d-flex flex-wrap place-items-center justify-content-around align-middle gap-2">

  <div class="d-flex flex-fill flex-column place-items-center justify-content-around align-middle">
    <%= form.label :name, class: 'form-label small' %>
    <%= form.text_field :name, class: 'form-control form-control-sm' %>
  </div>

  <div class="d-flex flex-fill flex-column place-items-center justify-content-around align-middle">
    <%= form.label :cost, class: 'form-label small' %>
    <%= form.number_field :cost, class: 'form-control form-control-sm' %>
  </div>

  <div class="d-flex flex-fill flex-column place-items-center justify-content-around align-middle">
    <%= form.label :per, class: 'form-label small' %>
    <%= form.select :per, 
                    Oroshi::Material.pers
                    .keys.map { |per| [I18n.t("enums.oroshi_material.per.#{per}"), per] },
                    {}, 
                    class: 'form-select form-select-sm' %>
  </div>

  <div class="d-flex flex-fill flex-column place-items-center justify-content-around align-middle">
    <%= form.label :material_category_id, class: 'form-label small' %>
    <%= form.collection_select :material_category_id, 
                              Oroshi::MaterialCategory.all, 
                              :id, :name, 
                              { prompt: I18n.t('oroshi.material.material_category_id') }, 
                              { class: 'form-select form-select-sm' } %>
  </div>

  <div class="d-flex flex-fill flex-column place-items-center justify-content-around align-middle">
    <%= form.label :image, class: 'form-label small' %>
    <%= form.file_field :image, class: 'form-control form-control-sm' %>
  </div>

</div>

<div class="d-flex justify-content-end align-items-center align-middle mt-2">
  <div class="form-check form-switch">
    <%= form.check_box :active, 
                  { class: 'form-check-input', 
                    checked: @material.active?,
                    data: {
                      action: 'click->oroshi--dashboard#toggleActive',
                      refresh_targets: 'oroshi_material_category_materials'
                    } } %>
    <%= form.label :active, class: 'form-check-label', for: 'activeSwitch' %>
  </div>
</div>

app/views/oroshi/materials/_materials_modal_form.html.erb
<%= turbo_frame_tag 'materials_modal_form' do %>
  <%= form_with model: @material, 
                      data: {
                        action: 'oroshi--dashboard#modalFormSubmit:prevent',
                        refresh_target: 'oroshi_material_category_materials'
                      } do |form| %>
    <%= render 'form', form: form %>
    <%= form.submit '保存', class: 'btn btn-primary my-2' %>
  <% end %>
<% end %>

app/views/oroshi/materials/edit.html.erb
<%= turbo_frame_tag 'material',
                    class: 'card p-1' do %>
  <%= turbo_frame_tag 'material_category', 
                      src: edit_oroshi_material_category_path(@material.material_category),
                      loading: 'lazy',
                      class: 'card p-1 mb-2' %>
  <div class="d-flex gap-2">
    <% if @material.image.attached? %>
      <%= image_tag url_for(@material.image), 
                    class: 'img-thumbnail rounded',
                    style: 'height: 150px;' %>
    <% end %>

    <%= form_with model: @material,
                  class: 'rounded p-2 flex-grow-1',
                  data: {
                    controller: 'oroshi--supply-settings-form'
                  } do |form| %>
      <%= render 'form', form: form %>
    <% end %>
  </div>
<% end %>

app/views/oroshi/materials/image.html.erb
<%= turbo_frame_tag 'material_image' do %>
  <%= image_tag url_for(@material.image), 
                class: 'img-thumbnail rounded',
                style: 'height: 150px;' %>
<% end %>

app/views/oroshi/materials/images.html.erb
<%= turbo_frame_tag 'material_images' do %>
  <% if @materials && @materials.any? %>
    <div class="d-flex justify-content-around place-items-center align-middle mb-1">
      <% @materials.each do |material| %>
        <% if material.image.attached? %>
          <%= image_tag url_for(material.image), 
                        class: 'img-thumbnail rounded',
                        style: 'height: 70px;' %>
        <% end %>
      <% end %> 
    </div>
  <% end %> 
<% end %>

app/views/oroshi/materials/index.html.erb
<%= turbo_frame_tag 'oroshi_material_category_materials' do %>
  <div class="d-flex flex-column align-items-center flex-lg-row align-items-lg-start justify-content-around gap-2">
    <div class="material-navigation card overflow-auto" style="min-width: 15rem; max-height: 75vh;">
      <div class="p-2 d-flex justify-content-between align-items-center align-middle">
        <h6 class="mb-0">製造材料</h6>
      </div>
      <% if @materials.exists? %>
        <div class="list-group overflow-y-scroll small m-1">
          <% @materials.each do |material| %>
            <% link_class = 'list-group-item list-group-item-action d-flex justify-content-between align-items-start' %>
            <% link_class += ' active' if @materials.first == material %>
            <% link_class += ' list-group-item-light opacity-50' unless material.active %>
            <%= link_to edit_oroshi_material_path(material),
                        class: link_class,
                        data: {
                          turbo_frame: 'material',
                          action: 'oroshi--dashboard#toggleActiveListItem:passive',
                        } do %>
              <div class="ms-2 me-auto">
                <div class="fw-bold"><%= material.name %></div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <div class="alert alert-warning small m-2" role="alert">
          製造材料が登録されていません。まずは製造材料を登録してください。
        </div>
      <% end %>
      <h6 class="card-subtitle p-2 d-flex justify-content-between align-items-center align-middle">
        <%= content_tag :div, class: 'form-check form-switch d-flex justify-content-between align-items-center align-middle' do %>
          <%= content_tag :input, 
                          nil, 
                          class: 'form-check-input me-2', 
                          type: 'checkbox', 
                          id: 'activeToggle', 
                          data: { 
                            action: 'change->oroshi--dashboard#toggleShowInactive',
                            target: 'oroshi_material_category_materials'
                          }, 
                          checked: @show_inactive %>
          <%= label_tag 'activeToggle', '全て表示', class: 'form-check-label' %>
        <% end %>
        <%= link_to '追加',
              new_oroshi_material_path,
              class: 'btn btn-sm btn-success',
              data: {
                turbo_frame: 'oroshi_modal_content',
                action: 'oroshi--dashboard#showModal:passive'
              } %>
      </h6>
    </div>
    <div class="material-settings flex-grow-1">
      <% if @materials.exists? %>
        <%= turbo_frame_tag 'material', 
                            src: edit_oroshi_material_path(@materials.first),
                            loading: 'lazy',
                            class: 'card p-1' %>
      <% else %>
        <div class="alert alert-warning small" role="alert">
          製造材料が登録されていません。まずは製造材料を登録してください。
        </div>
      <% end %>
    </div>  
  </div>
<% end %>

app/views/oroshi/materials/new.html.erb
<%= turbo_frame_tag 'oroshi_modal_content', class: 'modal-content' do  %>
  <div class="modal-header">
    <h5 class="modal-title">新しい製造材料を作成する</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <%= render 'materials_modal_form' %>
  </div>
<% end %>

app/views/oroshi/materials/update.html.erb
<%= turbo_frame_tag 'oroshi_modal_content', class: 'modal-content' do  %>
  <div class="modal-header">
    <h5 class="modal-title">製造材料を編集する</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    <%= render 'materials_modal_form' %>
    <div class="alert alert-success" role="alert">
      製造材料は正常に更新されました。
    </div>
  </div>
<% end %>