config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # SIDEKIQ
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # WELCOME/INDEX
  root 'welcome#index'

  # OROSHI
  namespace :oroshi do
    root to: 'dashboard#index'

    namespace :dashboard do
      %w[home suppliers_organizations supply_types
         shipping buyers materials products stats company].each do |tab|
        get tab
      end
      get 'subregions'
      post 'company_settings'
    end

    resources :supply_reception_times, except: %i[destroy show]

    resources :supplier_organizations, except: %i[show destroy] do
      get 'load', on: :collection
      get 'load', on: :member
      resources :suppliers, only: %i[new index]
    end

    resources :suppliers, except: %i[destroy show]

    resources :supply_types, except: %i[destroy show] do
      get 'load', on: :collection
      get 'load', on: :member
      resources :supply_type_variations, only: %i[new index]
    end

    resources :supply_type_variations, except: %i[destroy show]

    resources :supply_dates, param: :date, except: :destroy do
      post 'entry/:supplier_organization_id/:supply_reception_time_id',
           on: :member, to: 'supply_dates#entry', as: :entry
      get 'checklist/:subregion_ids/:supply_reception_time_ids',
          on: :member, to: 'supply_dates#checklist', as: :checklist
      get 'supply_invoice_actions', on: :collection
      get 'supply_price_actions', on: :collection
      post 'set_supply_prices', on: :collection
    end

    resources :supplies, only: %i[index show update] # new and create are handled by supply_dates
    get 'supplies/entry', to: 'supplies#new', as: :supply_entry

    get 'invoices/preview', as: :invoice_preview, to: 'invoices#preview'
    resources :invoices do
      get :send_mail_now, on: :member
      get :mail_notification_preview, on: :member
    end

    resources :shipping_organizations, except: :destroy do
      get 'load', on: :collection
      get 'load', on: :member
      resources :shipping_methods, only: %i[new index]
    end

    resources :shipping_methods, except: %i[destroy show]

    resources :buyers, except: %i[destroy show] do
      get 'orders/:date', on: :member, to: 'buyers#bundlable_orders', as: :bundlable_orders
    end

    resources :shipping_receptacles, except: %i[destroy show] do
      get 'image', on: :member
      get 'estimate_per_box_quantity/:product_variation_id',
          to: 'shipping_receptacles#estimate_per_box_quantity',
          on: :member
    end

    resources :packagings, except: %i[destroy show] do
      get 'image', on: :member
      get 'images', on: :collection
    end

    resources :material_categories, except: %i[destroy show] do
      resources :materials, only: %i[index]
    end

    resources :materials, except: %i[index destroy show] do
      get 'image', on: :member
      get 'images', on: :collection
    end

    resources :products, except: %i[destroy show] do
      get 'load', on: :collection
      get 'load', on: :member
      resources :product_variations, only: %i[new index]
      get 'material_cost/:shipping_receptacle_id/:item_quantity/:receptacle_quantity/:freight_quantity',
          on: :member,
          to: 'products#material_cost'
      patch 'update_positions', on: :collection
    end

    resources :product_variations, except: %i[destroy show] do
      get 'load', on: :collection
      get 'load', on: :member
      get 'image', on: :member
      get 'cost', on: :member
    end

    resources :production_zones, except: %i[destroy show]

    get 'orders/calendar', to: 'orders#calendar', as: :orders_calendar
    get 'orders/calendar/orders', to: 'orders#calendar_orders', as: :calendar_orders
    get 'orders(/:date)', to: 'orders#index', as: :orders
    get 'orders(/:date)/new', to: 'orders#new', as: :new_order
    post 'orders/from_template/:template_id', to: 'orders#new_order_from_template', as: :new_order_from_template
    delete 'orders/templates/:template_id', to: 'orders#destroy_template', as: :delete_template
    patch 'orders/:id/quantity_update', to: 'orders#quantity_update', as: :quantity_update_order
    patch 'orders/:id/price_update', to: 'orders#price_update', as: :price_update_order

    scope 'orders/:date', as: :orders do
      %w[orders templates production shipping sales revenue].each do |route|
        get "/#{route}", to: "orders##{route}", as: route.to_sym
      end
      get '/buyer_sales/:buyer_id', to: 'orders#buyer_sales', as: :buyer_sales
      get '/supply_volumes', to: 'orders#supply_volumes', as: :order_supply_volumes
      get '/product_inventories', to: 'orders#product_inventories', as: :order_product_inventories
      get '/production_view/:production_view', to: 'orders#production_view', as: :order_production_view
    end

    resources :orders, except: %i[index new show] do
      get 'show', to: 'orders#show', as: :show
    end

    resources :product_inventories, except: %i[destroy] do
      resources :production_requests, only: %i[index]
    end

    resources :production_requests, except: %i[index] do
      get 'convert/:date(/:product_id)', on: :collection, to: 'production_requests#convert', as: :convert
    end
  end

  # ASYNC AND JS
  get '/load_rakuten_orders/:date' => 'welcome#load_rakuten_orders', as: 'load_rakuten_orders'
  get '/load_funabiki_order/:date' => 'welcome#load_funabiki_orders', as: 'load_funabiki_orders'
  get '/load_yahoo_orders/:date' => 'welcome#load_yahoo_orders', as: 'load_yahoo_orders'
  get '/load_infomart_orders/:date' => 'welcome#load_infomart_orders', as: 'load_infomart_orders'
  get '/reciept/', as: 'reciept', to: 'welcome#reciept'
  get '/insert_receipt_data' => 'welcome#insert_receipt_data', as: 'insert_receipt_data'

  # WELCOME WIDGETS
  get :daily_expiration_cards, controller: :welcome
  get :rakuten_orders_fp, controller: :welcome
  get :receipt_partial, controller: :welcome
  get :front_infomart_orders, controller: :welcome
  get :infomart_shinki_modal, controller: :welcome
  get :funabiki_orders_partial, controller: :welcome
  get :funabiki_orders_modal, controller: :welcome
  get :yahoo_orders_partial, controller: :welcome
  get :new_yahoo_orders_modal, controller: :welcome
  get :rakuten_shinki_modal, controller: :welcome
  get :charts_partial, controller: :welcome
  get :printables, controller: :welcome

  # FORCAST
  get 'forcasts(/:date)' => 'forcasts#index', as: 'forcasts'
  get 'fetch_week_forcast/:date' => 'forcasts#fetch_week_forcast', as: 'fetch_week_forcast'
  get :week_forcast, controller: :forcasts
  get 'fetch_forcast_calendar_counts(/:date)', as: :fetch_forcast_calendar_counts,
                                               to: 'forcasts#fetch_forcast_calendar_counts', defaults: { format: 'js' }
  get 'fetch_forcast_calendar_forcasts(/:date)', as: :fetch_cforcast_alendar_forcasts,
                                                 to: 'forcasts#fetch_forcast_calendar_forcasts', defaults: { format: 'js' }
  get 'forcast_calendar_event_tippy/:date', as: :forcast_calendar_event_tippy,
                                            to: 'forcasts#forcast_calendar_event_tippy'
  get 'count_calendar_event_tippy/:date', as: :count_calendar_event_tippy, to: 'forcasts#count_calendar_event_tippy'

  # ANALYSIS
  get 'analysis' => 'analysis#index', as: 'analysis'
  get '/fetch_analysis' => 'analysis#fetch_analysis', as: 'fetch_analysis'
  get :total_profit_estimate_analysis_chart_partial, controller: :analysis
  get :market_profit_analysis_chart_partial, controller: :analysis
  get :oyster_sales_kilo_price_analysis_chart_partial, controller: :analysis
  get :oyster_market_kilo_price_analysis_chart_partial, controller: :analysis
  get :oyster_volume_analysis_chart_partial, controller: :analysis
  get :online_shop_order_count_chart_partial, controller: :analysis
  get :online_shop_order_sales_chart_partial, controller: :analysis
  get :furusato_order_count_chart_partial, controller: :analysis

  # ANALYSIS CHARTS
  get '/fetch_chart/:chart_params' => 'analysis#fetch_chart', as: 'fetch_chart'
  get '/market_profit_analysis_chart' => 'analysis#market_profit_analysis_chart', as: 'market_profit_analysis_chart'
  get '/total_profit_estimate_analysis_chart' => 'analysis#total_profit_estimate_analysis_chart',
      as: 'total_profit_estimate_analysis_chart'
  get '/oyster_sales_kilo_price_analysis_chart' => 'analysis#oyster_sales_kilo_price_analysis_chart',
      as: 'oyster_sales_kilo_price_analysis_chart'
  get '/oyster_market_kilo_price_analysis_chart' => 'analysis#oyster_market_kilo_price_analysis_chart',
      as: 'oyster_market_kilo_price_analysis_chart'
  get '/oyster_volume_analysis_chart' => 'analysis#oyster_volume_analysis_chart', as: 'oyster_volume_analysis_chart'
  get '/online_shop_order_count_chart' => 'analysis#online_shop_order_count_chart', as: 'online_shop_order_count_chart'
  get '/online_shop_order_sales_chart' => 'analysis#online_shop_order_sales_chart', as: 'online_shop_order_sales_chart'
  get '/furusato_order_count_chart' => 'analysis#furusato_order_count_chart', as: 'furusato_order_count_chart'

  # MESSAGES
  get '/messages/:id/download(/:file_name)', to: 'messages#download', as: 'download_message'
  get '/messages' => 'messages#index', as: 'messages'
  get '/messages/:id/:turbo_action' => 'messages#show', as: 'message'
  delete '/messages/:id' => 'messages#destroy', as: 'destroy_message'
  get '/message/:id', to: 'messages#content', as: 'message_content'
  get '/message/refresh/:id', to: 'messages#refresh', as: 'refresh_message'

  # FROZEN OYSTERS
  resources :frozen_oysters
  get '/insert_frozen_data' => 'frozen_oysters#insert_frozen_data', as: 'insert_frozen_data'

  # EXPIRATION CARDS
  resources :expiration_cards do
    get 'download/:file_name', on: :member, constraints: { format: 'pdf' },

app/models/expiration_card.rb
class ExpirationCard < ApplicationRecord
  has_one_attached :file

  def self.sakoshi_str
    '兵庫県坂越海域'
  end

  def self.aioi_str
    '兵庫県相生海域'
  end

  def self.today
    Time.zone.today
  end

  def self.nengapi_maker(date, plus)
    (date + plus).strftime('%Y年%m月%d日')
  end

  def self.sakoshi_exp_card(man_date_num, exp_day_num, print_made_on: true)
    where(
      ingredient_source: sakoshi_str,
      manufactuered_date: nengapi_maker(today, man_date_num),
      expiration_date: nengapi_maker(today, exp_day_num),
      made_on: print_made_on,
      shomiorhi: true
    ).first
  end

  def self.sakoshi_sanbaitai
    find_by(product_name: '殻付き かき（三倍体）')
  end

  def self.muji(is_sakoshi: true)
    where(
      ingredient_source: is_sakoshi ? sakoshi_str : aioi_str,
      manufactuered_date: '',
      expiration_date: '',
      made_on: true
    ).first
  end

  def self.sakoshi_frozen
    where(
      product_name: '冷凍殻付き牡蠣（プロトン凍結）',
      ingredient_source: sakoshi_str
    ).first
  end

  def self.aioi_exp_card(man_date_num, exp_day_num, print_made_on: true)
    where(
      ingredient_source: aioi_str,
      manufactuered_date: nengapi_maker(today, man_date_num),
      expiration_date: nengapi_maker(today, exp_day_num),
      made_on: print_made_on,
      shomiorhi: true
    ).first
  end

  def self.aioi_frozen
    where(
      product_name: '冷凍殻付き牡蠣（プロトン凍結）',
      ingredient_source: aioi_str
    ).first
  end

  def create_pdf
    save unless id
    pdf = ShellCard.new(id)
    io = StringIO.new pdf.render
    file.attach(io:, content_type: 'application/pdf', filename:)
    save
    pdf = nil
    io = nil
    GC.start
  end

  def filename
    "#{product_name}-#{manufactuered_date}-#{expiration_date}-#{manufactured_only}-カード.pdf"
  end

  def manufactured_only
    made_on ? '（製造日なし）' : ''
  end

  def print_shomiorhi
    shomiorhi ? ' 消    費    期    限' : ' 賞    味    期    限'
  end

  def shomiorhi_string
    shomiorhi ? '消費期限' : '賞味期限'
  end
end

app/controllers/expiration_cards_controller.rb
class ExpirationCardsController < ApplicationController
  before_action :set_expiration_card
  before_action :check_status

  def check_status
    return unless !current_user.approved? || current_user.supplier? || current_user.employee? || current_user.user?

    flash[:notice] = 'そのページはアクセスできません。'
    redirect_to root_path, error: 'そのページはアクセスできません。'
  end

  # GET /expiration_cards
  # GET /expiration_cards.json
  def index
    @expiration_cards = ExpirationCard.all.order(:created_at).reverse
  end

  # GET /expiration_cards/1
  # GET /expiration_cards/1.json
  def show; end

  # GET /expiration_cards/new
  def new; end

  # GET /expiration_cards/1/edit
  def edit; end

  def regenerate
    message = Message.new(user: current_user.id, model: 'expiration_card', state: false,
                          message: "#{Time.zone.today.to_date}のセルカードを作成中…", data: { expiration: (DateTime.now + 12.hours) })
    message.save
    ExpirationRegenerationWorker.perform_async(message.id)
    head :ok
  end

  def set_shomiorhi(card, params)
    params[:shomiorhi].to_i.zero? ? (card.shomiorhi = false) : (card.shomiorhi = true)
  end

  # POST /expiration_cards
  # POST /expiration_cards.json
  def create
    if ExpirationCard.exists?(expiration_card_params)
      respond_to do |format|
        format.html { redirect_to @expiration_card.find(expiration_card_params), notice: 'このカードはもう作られた。' }
        format.json { render :show, status: :ok, location: @expiration_card }
      end
    else
      @expiration_card = ExpirationCard.new(expiration_card_params)
      set_shomiorhi(@expiration_card, expiration_card_params)
      @expiration_card.create_pdf

      respond_to do |format|
        if @expiration_card.save
          format.html { redirect_to @expiration_card, notice: '賞味期限カードを作成しました。' }
          format.json { render :show, status: :created, location: @expiration_card }
        else
          format.html { render :new }
          format.json { render json: @expiration_card.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /expiration_cards/1
  # PATCH/PUT /expiration_cards/1.json
  def update
    if @expiration_card.file.attached?
      @expiration_card.file.purge
      @expiration_card.update(expiration_card_params)
      set_shomiorhi(@expiration_card, expiration_card_params)
      @expiration_card.create_pdf
      respond_to do |format|
        if @expiration_card.update(expiration_card_params)
          format.html { redirect_to @expiration_card, notice: '賞味期限カードを編集しました。' }
          format.json { render :show, status: :ok, location: @expiration_card }
        else
          format.html { render :edit }
          format.json { render json: @expiration_card.errors, status: :unprocessable_entity }
        end
      end
    else
      destroy
    end
  end

  # DELETE /expiration_cards/1
  # DELETE /expiration_cards/1.json
  def destroy
    @expiration_card.file&.purge
    @expiration_card.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@expiration_card) }
      format.html { redirect_to expiration_cards_url, notice: '賞味期限カードを削除しました。' }
      format.json { head :no_content }
    end
  end

  def download
    if @expiration_card.file.attached?
      send_data @expiration_card.file.download,
                filename: @expiration_card.file.blob.filename.to_s,
                type: 'application/pdf',
                disposition: 'inline'
    else
      redirect_to expiration_cards_path, alert: 'ファイルが見つかりません。'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expiration_card
    @expiration_card = if params[:id]
                         ExpirationCard.find(params[:id])
                       else
                         ExpirationCard.new(new_params)
                       end
  end

  def new_params
    params.permit(:product_name, :manufacturer_address, :manufacturer, :ingredient_source, :storage_recommendation,
                  :consumption_restrictions, :manufactuered_date, :expiration_date, :made_on, :shomiorhi)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def expiration_card_params
    params.require(:expiration_card).permit(:product_name, :manufacturer_address, :manufacturer, :ingredient_source,
                                            :storage_recommendation, :consumption_restrictions, :manufactuered_date, :expiration_date, :made_on, :shomiorhi)
  end
end

app/helpers/expiration_cards_helper.rb
module ExpirationCardsHelper
end

app/views/expiration_cards/_form.html.erb
<script>
  $(document).ready(function(){
    var expirationDateRow = $("#made_on_date_row");
    var expirationCardMadeOn = $("#expiration_card_made_on");

    if(expirationCardMadeOn.is(':checked')){
      expirationDateRow.show();
    }else{
      expirationDateRow.hide();
    }

    expirationCardMadeOn.change(function(){
      expirationDateRow.toggle(this.checked);
    });
  });
</script>

<div class="container">

  <%= simple_form_for(@expiration_card) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="row form-inputs form-control-group">
      <div class="col-md-6 col-sm-12 m-auto">
        <table class="table table-sm table-bordered">
          <tr>
            <th>名称</th>
            <td><%= f.text_field :product_name, class: 'form-control'%></td>
          </tr>
          <tr>
            <th>加工所所在地</th>
            <td><%= f.text_field :manufacturer_address, class: 'form-control'%></td>
          </tr>
          <tr>
            <th>加工者</th>
            <td><%= f.text_field :manufacturer, class: 'form-control'%></td>
          </tr>
          <tr> 
            <th>採取海域</th>
            <td><%= f.text_field :ingredient_source, class: 'form-control'%></td>
          </tr>
          <tr>
            <th>用途</th>
            <td><%= f.text_field :consumption_restrictions, class: 'form-control'%></td>
          </tr>
          <tr>
            <th>保存温度</th>
            <td><%= f.text_field :storage_recommendation, class: 'form-control'%></td>
          </tr>
          <tr id="made_on_date_row">
            <th>製造年月日・時間</th>
            <td><%= f.text_field :manufactuered_date, class: 'form-control'%></td>
          </tr>
          <tr>
            <th>（賞味・消費）期限</th>
            <td><%= f.text_field :expiration_date, class: 'form-control'%></td>
          </tr>
          <tr>
            <th>「賞味」か「消費」</th>
            <td><%= f.input :shomiorhi, label: '', as: :radio_buttons, collection: [['0', '賞味期限'], ['1', '消費期限']], label_method: :second, value_method: :first, :style =>"display:inline", item_wrapper_class: 'float-start d-block ms-4 mt-2' %></td>
          </tr>
          <tr>
            <th colspan="2" class="text-center">製造年月日印刷： <%= f.check_box :made_on %></th>
          </tr>
        </table>
      </div>
    </div>

    <div class="form-actions mt-4 text-center m-auto">
      <%= f.button :submit, class: 'btn btn-success m-auto' %>
    </div>
  <% end %>
</div>

app/views/expiration_cards/edit.html.erb
<%= turbo_frame_tag 'app' do %>
  <div class="text-center m-auto">
    <h1>「セルーカード」修正</h1>

    <%= render 'form', expiration_card: @expiration_card %>

    <div class="w-100 m-auto text-center">
      <%= link_to '表示', @expiration_card , class: 'btn btn-secondary m-2' %> |
      <%= link_to '前へ', expiration_cards_path, class: 'btn btn-secondary m-2' %>
    </div>
  </div>
<% end %>

app/views/expiration_cards/index.html.erb
<%= turbo_frame_tag 'app' do %>
  <% title "Funabiki Online - （消費・賞味）期限カード" %>

  <div id="product_index" class="container">
    <div class="row align-middle">
      <div class="col">
        <div class="btn-group float-end" role="group" aria-label="Basic">
          <%= link_to '追加（坂越）', new_expiration_card_path(product_name: '殻付き かき', manufacturer: '株式会社 船曳商店', manufacturer_address: '兵庫県赤穂市中広1576-11', ingredient_source: '兵庫県坂越海域', storage_recommendation: '要冷蔵　0℃～10℃', consumption_restrictions: '生食用' , manufactuered_date: nengapi_today, expiration_date: nengapi_today_plus(4), made_on: 1, shomiorhi: 1), :class => "btn btn-success" %>
          <%= link_to '追加（相生）', new_expiration_card_path(product_name: '殻付き かき', manufacturer: '株式会社 船曳商店', manufacturer_address: '兵庫県赤穂市中広1576-11', ingredient_source: '兵庫県相生海域', storage_recommendation: '要冷蔵　0℃～10℃', consumption_restrictions: '生食用' , manufactuered_date: nengapi_today, expiration_date: nengapi_today_plus(4), made_on: 1, shomiorhi: 1), :class => "btn btn-success" %>
        </div>
      <hr/>

        <h1>（賞味・消費）期限カード</h1>
        
      </div>
    </div>

    <hr/>

    <%= turbo_frame_tag 'expiration_cards' do %>
      <div class="row">
        <% @expiration_cards.each do |expiration_card| %>
          <%= turbo_frame_tag dom_id(expiration_card), class: "col-md-6 col-sm-12" do %>
            <div class="card mb-4">
              <div class="card-header text-body-secondary small text-center">
                <div class="m-auto btn-group my-2">
                  <%= link_to icon("card-heading"), 
                              (expiration_card.file ? expiration_card.file.url : expiration_card.download.url), 
                              class: 'btn btn-info popover-focus-top exp_card tippy', 
                              target: "_blank",
                              data: {
                                tippy_content: exp_card_popover(expiration_card),
                                controller: 'tippy',
                                turbo_frame: 'app'
                              } %>
                  <%= link_to icon("pencil-square", class: "text-success"), 
                              edit_expiration_card_path(expiration_card), 
                              class: 'btn btn-info tippy', 
                              data: {
                                tippy_content: "編集する",
                                controller: 'tippy',
                                turbo_frame: 'app'
                              } %>
                  <%= link_to icon("trash-fill", 
                              class: "text-danger"), 
                              expiration_card, 
                              class: 'btn btn-info tippy',
                              data: {
                                confirm: '削除していいですか?',
                                controller: 'tippy',
                                tippy_content: '削除する',
                                turbo_method: 'delete',
                                turbo_frame: 'app'
                              } %>
                  <%= link_to icon("subtract", class: "text-success"), 
                              new_expiration_card_path(expiration_card.attributes), 
                              class: 'btn btn-info tippy', 
                              data: {
                                tippy_content: "複数する",
                                controller: 'tippy',
                                turbo_frame: 'app'
                              } %>
                </div>
              </div>

              <table class="table table-sm table-bordered rounded m-auto my-2" style="font-size: 0.75em; max-width: 450px;">
                <tr>
                  <th>名称</th>
                  <td><%= expiration_card.product_name %></td>
                </tr>
                <tr>
                  <th>加工所所在地</th>
                  <td><%= expiration_card.manufacturer_address %></td>
                </tr>
                <tr>
                  <th>加工者</th>
                  <td><%= expiration_card.manufacturer %></td>
                </tr>
                <tr>
                  <th>採取海域</th>
                  <td><%= expiration_card.ingredient_source %></td>
                </tr>
                <tr>
                  <th>用途</th>
                  <td><%= expiration_card.consumption_restrictions %></td>
                </tr>
                <tr>
                  <th>保存温度</th>
                  <td><%= expiration_card.storage_recommendation %></td>
                </tr>
                <% if expiration_card.made_on %>
                  <tr>
                    <th>製造年月日</th>
                    <td><%= expiration_card.manufactuered_date %></td>
                  </tr>
                <% end %>
                <tr>
                  <th><%= expiration_card.print_shomiorhi %></th>
                  <td><%= expiration_card.expiration_date %></td>
                </tr>
              </table>

              <div class="card-footer text-body-secondary small text-center">
                <%= time_ago_in_words(expiration_card.created_at) %>前に作成
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
    

  </div>
<% end %>

app/views/expiration_cards/new.html.erb
<%= turbo_frame_tag 'app' do %>
  <div class="container text-center">
    <h1 class="mb-4">「セルーカード」作成</h1>

    <%= render 'form', expiration_card: @expiration_card %>

    <%= link_to '前へ', expiration_cards_path, class: 'btn btn-secondary m-2' %>
  </div>
<% end %>

app/views/expiration_cards/show.html.erb
<%= turbo_frame_tag 'app' do %>
  <% title "Funabiki Online - （賞味・消費）期限カード" %>

  <div class="container">
    <div class="row align-middle">
      <div class="col">

        <div class="btn-group float-end" role="group" aria-label="Basic">
          <%= link_to 'ダウンロード', (@expiration_card.file ? @expiration_card.file.url : @expiration_card.download.url), class: 'btn btn-info' %>
          <%= link_to 'カードトップへ', expiration_cards_path, class: 'btn btn-secondary' %>
        </div>
      <hr/>

        <h1>（賞味・消費）期限カード</h1>
        
      </div>
    </div>
    <p id="notice"><%= notice %></p>

    <hr/>

    <table class="table table-sm table-bordered border rounded w-50">
      <tr>
        <th>名称</th>
        <td><%= @expiration_card.product_name %></td>
      </tr>
      <tr>
        <th>加工所所在地</th>
        <td><%= @expiration_card.manufacturer_address %></td>
      </tr>
      <tr>
        <th>加工者</th>
        <td><%= @expiration_card.manufacturer %></td>
      </tr>
      <tr>
        <th>採取海域</th>
        <td><%= @expiration_card.ingredient_source %></td>
      </tr>
      <tr>
        <th>用途</th>
        <td><%= @expiration_card.consumption_restrictions %></td>
      </tr>
      <tr>
        <th>保存温度</th>
        <td><%= @expiration_card.storage_recommendation %></td>
      </tr>
      <tr>
        <th>製造年月日</th>
        <td><%= @expiration_card.manufactuered_date %></td>
      </tr>
      <tr>
        <th><%= @expiration_card.print_shomiorhi %></th>
        <td><%= @expiration_card.expiration_date %></td>
      </tr>
    </table>

  </div>
<% end %>